CLASS zcl_ent_auth DEFINITION PUBLIC FINAL CREATE PUBLIC.
 PUBLIC SECTION.
  CLASS-METHODS check_company IMPORTING company TYPE bukrs RAISING zcx_ent_domain.
ENDCLASS.
CLASS zcl_ent_auth IMPLEMENTATION.
 METHOD check_company.
  AUTHORITY-CHECK OBJECT 'ZENT_COMP' ID 'BUKRS' FIELD company ID 'ACTVT' FIELD '02'.
  IF sy-subrc <> 0. RAISE EXCEPTION TYPE zcx_ent_domain. ENDIF.
 ENDMETHOD.
ENDCLASS.
