*& S/4HANA logistics 4 ✅
CLASS zcl_logistics_s4_4 DEFINITION PUBLIC.
  PUBLIC SECTION.
    METHODS: execute.
ENDCLASS.
CLASS zcl_logistics_s4_4 IMPLEMENTATION.
  METHOD execute.
  ENDMETHOD.
ENDCLASS.
