*& S/4HANA logistics 2 ✅
CLASS zcl_logistics_s4_2 DEFINITION PUBLIC.
  PUBLIC SECTION.
    METHODS: execute.
ENDCLASS.
CLASS zcl_logistics_s4_2 IMPLEMENTATION.
  METHOD execute.
  ENDMETHOD.
ENDCLASS.
